import { Restaurant } from "@/types/index";

export const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "The Golden Fork",
    cuisine: ["italian_restaurant"],
    rating: 4.5,
    priceLevel: "PRICE_LEVEL_MODERATE",
    photoUrl: "https://placehold.co/400x600",
    address: "123 Main St",
    location: { lat: 0, lng: 0 },
    totalRatings: 142,
    openNow: true,
    googleMapsUri: null,
  },
  {
    id: "2",
    name: "Sakura Garden",
    cuisine: ["japanese_restaurant"],
    rating: 4.7,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    photoUrl: "https://placehold.co/400x600",
    address: "456 Oak Ave",
    location: { lat: 0, lng: 0 },
    totalRatings: 218,
    openNow: true,
    googleMapsUri: null,
  },
  {
    id: "3",
    name: "Burger Republic",
    cuisine: ["american_restaurant"],
    rating: 4.2,
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    photoUrl: "https://placehold.co/400x600",
    address: "789 Elm Rd",
    location: { lat: 0, lng: 0 },
    totalRatings: 95,
    openNow: false,
    googleMapsUri: null,
  },
];
